spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/casino_platform
spring.datasource.username=casino_user
spring.datasource.password=casino_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

jwt.secret=NSedStA/GLFKtUz3SOIuyrchg6bzht1Uk+fNQ5unfNv2bYGwGbPPg7s7hWw2P98i47GJmegCxNCthEPFRQlhSA==
jwt.expiration-seconds=900
